"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmailerContext = void 0;
var msRest = require("@azure/ms-rest-js");
var packageName = "emailer";
var packageVersion = "0.0.0";
var EmailerContext = /** @class */ (function (_super) {
    __extends(EmailerContext, _super);
    /**
     * Initializes a new instance of the EmailerContext class.
     * @param [options] The parameter options
     */
    function EmailerContext(options) {
        var _this = this;
        if (!options) {
            options = {};
        }
        if (!options.userAgent) {
            var defaultUserAgent = msRest.getDefaultUserAgentValue();
            options.userAgent = packageName + "/" + packageVersion + " " + defaultUserAgent;
        }
        _this = _super.call(this, undefined, options) || this;
        _this.baseUri = options.baseUri || _this.baseUri || "http://localhost";
        _this.requestContentType = "application/json; charset=utf-8";
        return _this;
    }
    return EmailerContext;
}(msRest.ServiceClient));
exports.EmailerContext = EmailerContext;
//# sourceMappingURL=emailerContext.js.map